# Тут указывается используемый в проекте язык программирования, можно указать несколько
language: python

# Далее, укажите версии python для которых нужно производить сборки
python:
  - "2.7"

# Команда для запуска тестов, в моем случае они запускаются именно так
script: python multi_tests/tests.py
